# Generated by Django 5.0.2 on 2024-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kRfblRpg8bm4PcJqIF6SRgHaFj?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
